title: API Lifecycle
description:  framework to define the API lifecycle in a modular and flexible way so that anyone can define their own version of the API lifecycle using a common set of elements actions being applied across standard definition of API operations.

image: https://postman-toolboxes2.s3.amazonaws.com/assets/api.png
url: https://apis.how
email: kin@postman.com

github_user: postman-open-technologies
github_repo: lifecycle
github_branch: main

version:      1.1.1
markdown:     kramdown

collections:
  blueprints:    
    permalink: /blueprints/:path/  
    output: true
  elements:    
    permalink: /elements/:path/  
    output: true    
  actions:    
    permalink: /actions/:path/  
    output: true       
  questions:    
    permalink: /questions/:path/  
    output: true       
  answers:    
    permalink: /answers/:path/  
    output: true       

defaults:
  - scope:
      type: blueprints
    values:
      layout: blueprints      
  - scope:
      type: elements
    values:
      layout: elements    
  - scope:
      type: actions
    values:
      layout: actions          
  - scope:
      type: answers
    values:
      layout: answers     
  - scope:
      type: questions
    values:
      layout: questions                