title: Products
description: Making digital products.

image: https://postman-toolboxes2.s3.amazonaws.com/assets/api.png

url: /
#url: /

email: kin@postman.com

github_user: postman-open-technologies
github_repo: lifecycle
github_branch: main

version:      1.1.1
markdown:     kramdown

token: token

episodes_base_url: https://umy5jz66lk.execute-api.us-west-1.amazonaws.com/staging
vocabulary_base_url: https://47n3z44a22.execute-api.us-west-1.amazonaws.com/staging
tasks_base_url: https://umy5jz66lk.execute-api.us-west-1.amazonaws.com/staging