title: API Lifecycle
description: [Just a Proof of Concept]

image: https://postman-toolboxes2.s3.amazonaws.com/assets/api.png
url: https://postman-toolboxes.github.io/api-knowledge
email: kin@postman.com

github_user: postman-open-technologies
github_repo: lifecycle
github_branch: main

version:      1.1.1
markdown:     kramdown

collections:
  blueprints:    
    permalink: /blueprints/:path/  
    output: true
  elements:    
    permalink: /elements/:path/  
    output: true    

defaults:
  - scope:
      type: blueprints
    values:
      layout: blueprints      
  - scope:
      type: elements
    values:
      layout: elements          