---
name: Generate Collection From Mobile Application
description: A blueprint for beginning the API lifecycle by generating a collection from a mobile application.
image: https://postman-toolboxes2.s3.amazonaws.com/assets/api.png
tags:
  - OpenAPI
  - Prototype-First
stage: Active
order: 3
areas:

  - label: Proxy
    description: Proxy traffic for mobile application.
  - label: Document
    description: Provide humans with documentation.  
  - label: Test
    description: Ensure an API has proper testing.  
  - label: Discovery
    description: Ensure an API is discoverable.  